### ISSUE TITLE
Extra green lines

### ISSUE THREAD

**Issue by art1415926535** [lirantal/dockly#106]
## Actual Behavior
I have 5 extra green lines at the bottom of the window.

![image](https://user-images.githubusercontent.com/5222234/56305918-eee4f500-6149-11e9-83f9-bf32fbe5902c.png)

## Steps to Re-produce the Problem
  1. Install Dockly.
  2. Run Dockly from cmd.exe.

## Context
- Operating System: Windows 10
- Node.js version (run `node --version`): v10.15.2
- Package version: 3.10.5
- Docker version (run `docker --version`): Docker version 18.03.0-ce, build 0520e24302
- Is docker installed locally? Yes.
- Does this file exists `/var/run/docker.sock` ? No.

**Comment by lirantal** [comment]
I have that too (as in, it's expected :))

![image](https://user-images.githubusercontent.com/316371/56317606-d2ef4c80-6165-11e9-989a-d069ade17ffc.png)

**Comment by art1415926535** [comment]
Can I remove it to increase logs box?

Like this:
![dockly-demo-2](https://cloud.githubusercontent.com/assets/316371/25682867/c5212216-3027-11e7-8f36-72d38516d2af.gif)

**Comment by lirantal** [comment]
I see what you mean but for the new version we use a layout system which really has just one block set for the toolbar but due to automatic positioning it's taking up the relevant space.

See:
```
const CONTAINERS_GRID_LAYOUT = {
  'actionsMenu': [4, 4, 4, 4],
  'searchInput': [11, 0, 1, 12],
  'actionStatus': [6, 0, 1, 10],
  'containerInfo': [2, 2, 8, 8],
  'containerList': [0, 0, 6, 10],
  'containerLogs': [7, 0, 4, 12],
  'containerStatus': [0, 10, 2, 2],
  'containerUtilization': [2, 10, 3, 2],
  'containerVsImages': [5, 10, 2, 2],
  'help': [4, 4, 4, 4],
  'toolbar': [11, 0, 1, 12]
}
```

If you're able to figure out better spacing I'm happy to merge a PR

**Comment by lirantal** [comment]
@art1415926535 I'll close this issue out due to inactivity and currently no action planned on it. I'm also happy if you want to re-open and re-engage in the conversation on this!
