### ISSUE TITLE
Ability to read a specific docker-compose file

### ISSUE THREAD

**Issue by kbariotis** [lirantal/dockly#108]
This is a feature request. I was wondering if we could read a specific docker-compose file so you can manage only the containers defined in that file.

On my local development, I have myriads of containers running but often times I want to inspect or manage only the containers of the specific project I am working on, which has its own docker-compose definition.

Thank you, loved this tool. 💯

**Comment by lirantal** [comment]
Hi @kbariotis 👋

I like this idea!

Happy to pick your brain on how something like this would work. WDYT on:
1. parse `docker-compose.yml` to flesh out the container names based on the `services` clause, and allow `container_name` for each one of them to override the actual name.
2. filter the list to show only these

Questions about functionality around this:
1. If you're in a directory that has a `docker-compose.yml` file it will be automatically picked up
2. Specifying a command line argument for a compose file
3. Should bulk capabilities like `stop all containers` available in the rich menu work for *all* containers or just for those detected in the compose mode?

**Comment by lirantal** [comment]
Will close for now :-)
