### ISSUE TITLE
Control characters when moving mouse in terminal

### ISSUE THREAD

**Issue by flowli** [lirantal/dockly#109]
## Expected Behavior
The same like entering the container shell with docker exec -it <hash> bash - which is being able to move the mouse over the terminal without outputting strange control characters.

## Actual Behavior
Output of strange control characters ;-)

## Steps to Re-produce the Problem

  1. use ddev to create a php environment, start it with "ddev start" (but maybe just any container)

  2. open dockly and enter the web container with the "l" key

  3. move the mouse over the console and see strange characters appear (without any typing)

## Context

- Operating System: MacOS
- Node.js version (run `node --version`): 10.13.0
- Package version: 3.11.0
- Docker version (run `docker --version`): 18.09.2
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? yes

**Comment by flowli** [comment]
An example of how this looks: <img width="1299" alt="Screenshot 2019-05-08 at 11 15 28" src="https://user-images.githubusercontent.com/2144428/57364048-9fab4680-7182-11e9-9741-e2cd18992b56.png">

**Comment by ybs5** [comment]
Me too.My environment is
* OS ubuntu18.10
* nodejs 8.11.4
* npm 5.8.0
* docker 18.09.6
* dockly 3.11.0

**Comment by seinick** [comment]
I have this issue.

- OS: Mac OS 10.14.5
- nodejs v10.15.3
- dockly 3.11.0

**Comment by lirantal** [comment]
I can reproduce the same issue indeed. Will take a look at a possible fix, or perhaps revert to opening the shell in a new window if that would work.

**Comment by lirantal** [comment]
@flowli @seinick @ybs5 as a workaround, after you're in the shell with `l`, can you type in the command `reset` and click return to see if that fixed it?

I could make that reset command run by default but then when you exit back to dockly interface you'd be left without a mouse so I'm still wondering if there's a proper fix for it.

**Comment by lirantal** [comment]
Seems we can enable and disable mouse tracking with:

enable:
```
printf '\e[?1000l'
```

disable:
```
printf '\e[?1000h'
```

So perhaps a script wrapping the login command that does this would work.
How critical is mouse support in the shell? :D

**Comment by seinick** [comment]
To me mouse support is completely unnecessary in the shell.

**Comment by flowli** [comment]
Full ack, no mouse needed.

**Comment by lirantal** [comment]
@flowli @seinick @ybs5 
can you please install the newer version of dockly: `npm install --global dockly@latest` and see if the fix I pushed solves the problem for you?

latest version should be 3.14.2
thanks!

**Comment by flowli** [comment]
Thanks for the update. Unfortunately when I press "l:shell" the status looks as follows:

<img width="785" alt="Screenshot 2019-09-20 at 00 44 11" src="https://user-images.githubusercontent.com/2144428/65286423-d4bba280-db3f-11e9-86b1-a41e8092b5c6.png">

**Comment by lirantal** [comment]
@flowli Oh indeed! I forgot that we are now whitelisting files when creating the dockly package.
I pushed a fixed version, can you `npm install -g dockly@latest` again and check it?

**Comment by flowli** [comment]
@lirantal Works now, Liran. ❤️from Erkrath, Germany

**Comment by lirantal** [comment]
thank you for the quick catch ❤️❤️❤️
