### ISSUE TITLE
Handling docker images

### ISSUE THREAD

**Issue by maku** [lirantal/dockly#111]
Is there a plan to also support to manage docker images?

**Comment by lirantal** [comment]
Shouldn't be too much trouble to add with the infrastructure we currently have that you can manage listing pretty easily.

The menu in `m` already has some quick access to image operations like pruning them all etc.
Could you mock out what you had in mind for the images and what kind of functionality would you need?

**Comment by maku** [comment]
Sounds great:
It would be great to be able to switch to a view (table) which provides the information you get with the command: `docker images`

Then it should be possible to navigate on the images. 
When an image is selected it would be nice to execute certain actions 

- get inspect information (`docker image inspect`)
- remove an image 
- force remove an image

Of course there are some "nice to have" function like filtering / search of images by name, examine which container belong to an image etc. :-)

**Comment by OmriBarZik** [comment]
If no one working on this feature I would like to give it a try.

**Comment by OmriBarZik** [comment]
this is what I've done so far, what do you think? Any suggestions?

![render1622353131525](https://user-images.githubusercontent.com/16163470/120094050-c13f4800-c126-11eb-8812-3a83aad1a313.gif)

**Comment by lirantal** [comment]
@OmriBarZik looks incredible!

Some comments:
1. I guess the expand logs toolbar option is irrelevant there? if so, I'd remove it.
2. How do you switch back to container listing? with toggling `v`, or something else?

Seems to me ready to send over a pull request so we can merge it in.

**Comment by OmriBarZik** [comment]
1. No Problem I will remove it.
2. You can go back to the container listing by pressing `v`
