### ISSUE TITLE
[Question] Install via apt

### ISSUE THREAD

**Issue by lonix1** [lirantal/dockly#122]
On a small VPS that doesn't have anything extra installed, it would be nice to be able to install a packaged version (e.g. apt).

Is this possible?

**Comment by lirantal** [comment]
It's been long years since I had worked closely to package management teams in Linux distribution so at the moment I'm probably not the best person to lead this. I'm happy however to assist in any way I can.

Did you notice that there's also a way to use dockly with docker?

**Comment by lonix1** [comment]
I've never done package management so wouldn't know where to start 😄 

I noticed the docker version but maybe that's overkill (for me). I like the idea of just running it from anywhere. I'll use the npm version for now. Thanks, it's a very nice tool.

**Comment by lirantal** [comment]
Cool thanks! :)
