### ISSUE TITLE
Text UI not displayed properly

### ISSUE THREAD

**Issue by strike-noir** [lirantal/dockly#123]
I'm liking dockly very much. But in my PuTTY terminal the TUI are not displayed properly.

[screenshot](https://www.dropbox.com/s/bc2j4q4geixjq3j/dockly.PNG?dl=0)

Am I missing a Node.js package or is PuTTY client not supported?

**Comment by lirantal** [comment]
Unfortunately I'm not entirely sure how to resolve that as the whole screen UI is managed by another library so I don't have any quick fix for that.

**Comment by strike-noir** [comment]
Here is what npm said about the packages. I hope you can help.

```
/usr/local/lib
├── dockly@3.14.4
└── marked@0.3.19

npm ERR! peer dep missing: marked@^0.3.3, required by marked-terminal@1.7.0
```

**Comment by lirantal** [comment]
@strike-noir do you have a problem running dockly? I didn't understand from the above comment if you are unable to install it

**Comment by norweeg** [comment]
@strike-noir it's not a bug.  You need to change your PuTTY settings.  
See https://github.com/lirantal/dockly/issues/50#issuecomment-536190949

**Comment by strike-noir** [comment]
Hey the options Enable VT100 fixes it. Thanks!

**Comment by lirantal** [comment]
@norweeg thanks for following up!
I'll go ahead and update the README with this
