### ISSUE TITLE
alternative key for refresh

### ISSUE THREAD

**Issue by hoegge** [lirantal/dockly#135]
## Current behaviour

Currently you press '=' to refresh the view, which is ok on a US keyboard. But a lot of keyboard have '=' on a shifted key, so you have to press shift+key every time you refresh

## Suggestion

Would you consider to change the shorcut key to \<space\> instead? 

It much easier to hit and the same for all keyboard layouts.

PS: Thanks for the best docker GUI ever

**Comment by lirantal** [comment]
That's a valid concern and I think that's a good idea too. Do you want to PR the change to the repo?

**Comment by hoegge** [comment]
OK - I'll try to see if I can figure it out and test it - brb

**Comment by hoegge** [comment]
Have changed it, run test and seems to work fine.

**Comment by hoegge** [comment]
Hi, Sorry for being ignorant. Do I need to do more to complete this (seems like the pull request went throug). Then I just close this issue (since it is assigned to me)?
Does it automatically update at NPM or do you have to do something for making a release?

**Comment by lirantal** [comment]
@hoegge indeed, there was an issue with releasing a new version to npm. Looking into it now.

**Comment by lirantal** [comment]
There we go, now there's a new dockly version released which should have this feature added.
Thanks for the ping @hoegge 👌
