### ISSUE TITLE
Containers removed after start of Dockly remain after refresh

### ISSUE THREAD

**Issue by norweeg** [lirantal/dockly#145]
## Expected Behavior
Containers which have been removed and are no longer displayed after refreshing Dockly

## Actual Behavior
The containers are still displayed as if they were still there

## Steps to Re-produce the Problem

  1. Create some containers

  2. Open Dockly

  3. Remove the containers from step 1

## Context

- Operating System: Linux raspi 5.4.0-1032-raspi aarch64
- Node.js version (run `node --version`): v12.21.0
- Package version:
- Docker version (run `docker --version`): Docker version 20.10.5, build 55c4c88
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 26
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1032-raspi
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 908.2MiB
 Name: raspi
 ID: WFVR:ZMCO:6VKS:QSOO:R46B:VP3P:APCD:QFOZ:4F2V:DQJ2:WJWZ:XMRL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by lirantal** [comment]
@norweeg if you remove the container and then press the `spacebar` to refresh the list, do they still show up or are they gone?

**Comment by norweeg** [comment]
Nope, they are still there.  I specifically had dockly open, ran a docker-compose up, docker-compose down, and then docker-compose up again and had the containers that were removed by docker-compose down displaying alongside the ones that were newly created when I brought it up again

**Comment by lirantal** [comment]
Oh, but isn't docker-compose down simply stopping them? they would still show up on the list, just in a stopped state.

**Comment by norweeg** [comment]
> Oh, but isn't docker-compose down simply stopping them? they would still show up on the list, just in a stopped state.

No, it removes them. docker-compose stop stops them.

**Comment by lirantal** [comment]
I think you're right. I may have been able to reproduce it. Looking at this.

**Comment by lirantal** [comment]
@norweeg managed to reproduce and fix, pushing now a new release.
Thanks for opening it!
