### ISSUE TITLE
Copy Container Id Showing In Services View

### ISSUE THREAD

**Issue by OmriBarZik** [lirantal/dockly#152]
## Expected Behavior
The option `copy container id` showing only in containers view

## Actual Behavior
`copy container id` showing only in all the views.

## Steps to Re-produce the Problem

  1. open dockly

  2. press v

## Context

- Operating System: windows 10 pro
- Node.js version (run `node --version`): v14.16.1
- Package version: main branch
- Docker version (run `docker --version`): 20.10.5
- Is docker installed locally? _yes_
- Do you have containers created? _yes_
- Does this file exists `/var/run/docker.sock` ? yes
- Output of `docker info`:
<details>
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.33GiB
 Name: docker-desktop
 ID: USTD:B5EU:H6TN:ONH3:DDZO:DEF3:BM6Y:LRKL:R6QT:22WL:Q6PJ:Z33T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
</details>

**Comment by lirantal** [comment]
You mean you'd like to have it in services view as well?

**Comment by OmriBarZik** [comment]
I mean that the option is visible but dose not function.
