### ISSUE TITLE
CI in PR's fails because of build_docs job

### ISSUE THREAD

**Issue by OmriBarZik** [lirantal/dockly#160]
## Expected Behavior
The `build_docs` job should not run when creating PR

We should add a check to the job to run only when the PR push to the master like in the [`release` job](https://github.com/lirantal/dockly/blob/master/.github/workflows/main.yml#L30).

## Actual Behavior
The `build_docs` job run and make the CI fails

## Steps to Re-produce the Problem

  1. create PR in a fork

## Context

**Not related**

- Operating System:
- Node.js version (run `node --version`):
- Package version:
- Docker version (run `docker --version`):
- Is docker installed locally?
- Do you have containers created?
- Does this file exists `/var/run/docker.sock` ?
- Output of `docker info`:

**Comment by lirantal** [comment]
Fixed in #161
