### ISSUE TITLE
Fix: upgrade blessed-contrib dep version to latest (4.9.0)

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#163]
## Expected Behavior

`blessed-contrib` version 4.9.0 has no vulnerable deps anymore.

## Actual Behavior

Current version has a few vulnerable deps (lodash and marked)

## Steps to Re-produce the Problem

  1. snyk test
  2. see rsults

**Comment by OmriBarZik** [comment]
Fixed in #166
