### ISSUE TITLE
The "return" key causes issues on the Containers view

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#174]
Same when in Containers view, pressing "Return" (to see the logs) and then "v" to change the view.
Error: Cannot read property 'update' of undefined

**Comment by OmriBarZik** [comment]
I can't replicate this bug, can you elaborate, please 🙏

**Comment by lirantal** [comment]
It was reported by someone on a reddit thread, can't replicate it either :(
Let's close for now.
