### ISSUE TITLE
Copying the container to the clipboard fails on some systems

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#175]
`Error: Error: Couldn't find thexsel binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel`

@OmriBarZik seems like `clipboardy` should be cross platform but it may also not be found in some systems. Perhaps worth to catch the error thrown in cases where it isn't available?

**Comment by OmriBarZik** [comment]
`clipboardy` has the `xsel` in its source code, so it is weird, but I agree that we should add a case where `clipboardy` won't work.
I'll do a PR today

**Comment by OmriBarZik** [comment]
after some research, I found out that `xsel` fails when you try to copy to a remote computer. 
if you will try to use dockly on a remote machine with ssh this may happen.
