### ISSUE TITLE
Remove Unused RP Checks

### ISSUE THREAD

**Issue by OmriBarZik** [lirantal/dockly#179]
I think we should remove this checks from the PR process:
 * `continuous-integration/travis-ci Expected`
 * `dockly`
 * `security/snyk - package.json (lirantal)`

They just make the status update wait indefinitely and the PR never 'passes', only 'waiting' or 'fail'.

**Comment by lirantal** [comment]
Indeed. Just updated the status checks to remove them.
Thanks!
