### ISSUE TITLE
[Bug]: Cannot find node module node:process

### ISSUE THREAD

**Issue by GimpMaster** [lirantal/dockly#194]
### What went wrong?

I installed dockly via npm install -g dockly. When running it I got this error

```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /usr/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs
- /usr/lib/node_modules/dockly/node_modules/blessed-contrib/lib/widget/markdown.js
- /usr/lib/node_modules/dockly/node_modules/blessed-contrib/index.js
- /usr/lib/node_modules/dockly/src/screen.js
- /usr/lib/node_modules/dockly/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs',
    '/usr/lib/node_modules/dockly/node_modules/blessed-contrib/lib/widget/markdown.js',
    '/usr/lib/node_modules/dockly/node_modules/blessed-contrib/index.js',
    '/usr/lib/node_modules/dockly/src/screen.js',
    '/usr/lib/node_modules/dockly/index.js'
  ]
}
```

### Your environment setup

- Operating System: Ubuntu 20.04 LTS
- Node.js version (run `node --version`): node 14.17.5
- Package version: npm: 6.14.14
- Docker version (run `docker --version`): Docker version 19.03.1, build 74b1e89
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-58-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: ontrac-sandbox
 ID: RDZI:46K6:SV3B:LZ6N:MFSC:S2AK:MP7R:44OL:AS2L:DX2T:2XZN:2MJV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by antoniofrignani** [comment]
Same error, Node v14.17.1, MacOS 12.0.1

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs
- /Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/blessed-contrib/lib/widget/markdown.js
- /Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/blessed-contrib/index.js
- /Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/src/screen.js
- /Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/marked-terminal/index.cjs',
    '/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/blessed-contrib/lib/widget/markdown.js',
    '/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/node_modules/blessed-contrib/index.js',
    '/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/src/screen.js',
    '/Users/antonio/.nvm/versions/node/v14.17.1/lib/node_modules/dockly/index.js'
  ]
}
```

**Comment by OmriBarZik** [comment]
Hey, @antoniofrignani @GimpMaster thanks for opening the issue!
It looks like we have a bug in version node versions 14.17.6 and lower, I'm working on a fix but in the meantime, you can update your node versions to 14.18.0 and Dockly will work

**Comment by lirantal** [comment]
@OmriBarZik nice quick catch!
Is this an issue with the marked dependency?

**Comment by lirantal** [comment]
As far as I can tell we don't actually have this issue anymore as I tested with v14.17.1:

![image](https://user-images.githubusercontent.com/316371/216183613-59bf555b-b086-4859-8369-9d94c5a55195.png)

And then running dockly, it starts off just fine:

![image](https://user-images.githubusercontent.com/316371/216183734-2121e464-7a2f-4169-91da-aee3939197cb.png)
