### ISSUE TITLE
Support docker contexts for remote hosts

### ISSUE THREAD

**Issue by neoromantic** [lirantal/dockly#195]
One can leverage docker contexts to manage remote docker host:

```
> docker context add my-remote-host ssh://ubuntu@goodit.works
```

Now, all docker commands are being run in this remote server, even docker-compose and whatever.

Sadly, dockly can't do that. I suppose, it could — it might be even quite easy to integrate?

Hope to hear what you think!

**Comment by OmriBarZik** [comment]
@neoromantic  That sounds like a great idea! I have created a PR to implement this
