### ISSUE TITLE
It would be great to see the port mappings in the containers view

### ISSUE THREAD

**Issue by techarch** [lirantal/dockly#198]
First, this is an awesome tool! Thank you for creating it! :-)
I found out about it in this week's edition of the Programmer Weekly newsletter (https://mailchi.mp/programmerweekly/programmer-weekly-issue-94?e=e8c11d0390).
It would really nice if there could be a column to show the port mappings in the Containers view, maybe in between the Command and State columns.

**Comment by lirantal** [comment]
Thanks for the kind words @techarch and for sharing with us. I hadn't realized it was also featured on Programmer Weekly 😍

The port mapping seems relevant and ideal to include in the list. Need to check there's enough real estate there in the screen with everything else. How would you format the entry in that column?

**Comment by techarch** [comment]
How about just like the -p syntax in docker run so 8080:80? And stack them if there is more than one port mapping.

**Comment by lirantal** [comment]
That makes sense.
Would you like to try and make the code changes and send over a pull request?
