### ISSUE TITLE
[Enhancement]: Add Vi Key Bindings

### ISSUE THREAD

**Issue by RilDev** [lirantal/dockly#199]
Hi there, thank you very much for this UI, it makes Docker very easy to use!

Would it be possible to add J and K to go up and down in the lists? Like it we could either press UP / DOWN or J / K to navigate without leaving the home row (like in Vim).

Thank you very much!

**Comment by lirantal** [comment]
Hi @RilDev, thanks for suggesting this. 
I think it makes a lot of sense, just need to check that the key bindings are indeed free for use :-)

Will take a look later on the weekend. In the meanwhile, if you wanted to take a look at the code and propose a pull request, I'd be happy to help you get that merged.

**Comment by RilDev** [comment]
Challenge accepted! Thanks for the offer!

**Comment by RilDev** [comment]
@lirantal So to what I understand, the up / down arrow binding is managed by `blessed-contrib`. Am I right?
If yes, I'll have to familiarize myself with this library this week-end!

I also went through `widgets` files and k / j look like they are indeed free.

**Comment by RilDev** [comment]
Yes it does help! Thanks!

**Comment by RilDev** [comment]
Challenge failed :(

To what I saw, there is no clear documentation for rebinding the arrow keys in the `blessed` library.
And the furthest I could go was to this file https://github.com/chjj/blessed/blob/master/lib/keys.js... but I don't have the skills / understanding needed to modify it and implement it in `dockly`.

Sorry about that!

**Comment by lirantal** [comment]
No worries at all and this is amazing you tried it!
I'll try to put some time in the next couple of weeks to work on it too and as I make progress I'll update you so you can make the relevant changes.

**Comment by lirantal** [comment]
@RilDev Ok, had a bit of time to tinker with this issue this morning

So, firsly, the base list widget that we use in dockly from the blessed library actually already supports a vi-type key binding. See from the [README docs](https://github.com/chjj/blessed#list-from-box): 
![image](https://user-images.githubusercontent.com/316371/159152021-9005dcf8-ee68-4425-b24c-87c43037cf2b.png)

This means that all the needed code change is to update the instantiation code for all list type widgets to support that option. You do it as follows:

diff --git a/src/widgetsTemplates/list.widget.template.js b/src/widgetsTemplates/list.widget.template.js
index da39b7c..532b525 100644
--- a/src/widgetsTemplates/list.widget.template.js
+++ b/src/widgetsTemplates/list.widget.template.js
@@ -88,6 +88,7 @@ class myWidget extends baseWidget(EventEmitter) {
       mouse: true,
       data: null,
       tags: true,
+      vi: true,
       interactive: true,
       border: 'line',
       hover: {

Simple enough, right? :-)

Go ahead and test that locally, and then feel free to raise a new pull request detailing the change and I'll happily merge it and release a new dockly version.

**Comment by RilDev** [comment]
Thank you @lirantal! I'll be experimenting with it and prepare a nice pull request as soon as possible!

**Comment by RilDev** [comment]
Alright, so I was able to test the `vi: true` key. It works well and doesn't deactivate the arrow keys, which is very convenient.
However, it doesn't work (yet) in the (m)enu.
So I'll be looking into it furthe!
