### ISSUE TITLE
[Bug]: A container with a single quote in the command will mess up the overview table (not showing the state and status columns anymore)

### ISSUE THREAD

**Issue by MetalArend** [lirantal/dockly#205]
### What went wrong?

If you have a container running that has a command with a single quote in it, like `sh -c 'tail -f /dev/null'`, it will show up in the overview. But the table highlights as if the command is the last column, and the State and Status columns are not populated for that container.

### Your environment setup

- Operating System: NixOS
- Node.js version (run `node --version`): running in the latest lirantal/dockly container
- Package version: running in the latest lirantal/dockly container
- Docker version (run `docker --version`): Docker version 20.10.7, build v20.10.7
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? yes
- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., 0.0.0+unknown)

Server:
 Containers: 22
  Running: 8
  Paused: 0
  Stopped: 14
 Images: 1633
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: v1.5.7
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.88
 Operating System: NixOS 21.05 (Okapi)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.31GiB
 Name: nixos
 ID: JMBO:UXHB:WA6C:HFWI:6W5O:I5PW:L3NR:TEZN:TNZQ:7VRJ:NFXS:4CYG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by lirantal** [comment]
Thanks for reporting @MetalArend. any chance you have a screenshot or that or an easily reproducible Dockerfile for us to test against?

**Comment by MetalArend** [comment]
Update on the issue: it's not the single quote that is the issue, I think it's the newline.

## step 1: create compose.yaml file

```
services:
  dockly:
    image: lirantal/dockly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      sh -c '
        node index.js
      '
```

## step 2: run docker-compose command

`docker-compose up -d`

## step 3: run dockly ;)

**Comment by lirantal** [comment]
Appreciate it! I'll take a look tonight and get back to you

**Comment by lirantal** [comment]
Thanks @MetalArend I was able to reproduce easily and have a fix in place :-)

**Comment by MetalArend** [comment]
Awesome! :rocket:
