### ISSUE TITLE
[Bug]: shell generates trash when I move the mouse

### ISSUE THREAD

**Issue by visionm45** [lirantal/dockly#219]
### What went wrong?

I am on manjaro linux and when I enter a shell then I move the mouse within the bounds of the newly opened terminal a lot of random characters are generated.

node --version
10.3.0

docker --version
Docker version 20.10.22, build 3a2c30b63a

docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.14.2)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323.m
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.85-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.14GiB
 Name: jadfs-compy
 ID: 3GKR:ORZC:DO2R:5AQS:HNOT:TCJG:Y7JD:EFXF:MV5Z:MNOO:4UUW:JBQV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Your environment setup

- Operating System:
- Node.js version (run `node --version`):
- Package version:
- Docker version (run `docker --version`):
- Is docker installed locally?
- Do you have containers created?
- Does this file exists `/var/run/docker.sock` ?
- Output of `docker info`:

**Comment by lirantal** [comment]
Apologies but I have no way of reproducing that, @visionm45.

Some things to consider:
- Could you upgrade your Node.js version? seems to be an unsupported and outdated one (v10 that you're using)
- Could perhaps use a different terminal interface program?

**Comment by jhaglund** [comment]
I would like this reopened -- I also have this problem.

I can connect to containers and use the shell in Dockly but if i move my mouse within my terminal window, the shell fills with what appear to be mouse coords like a twitch produces 5;62;12M, another twitch of the mouse 3;62;12M

It appears some terminal mode is changed with dockly to use the mouse -- the first screen lets me use the mouse in a graphical UI sorta way. It's not turning off in the shell? And when I exit dockly, the terminal no longer lets me select text, so it's effect goes beyond the app and messes with the terminal after its closed.

Ubuntu 22.04.4 LTS
Node v21.7.3
Dockly 3.24.1
Docker version 26.0.0, build 2ae903e
Docker is local

**Comment by lirantal** [comment]
Maybe we disable the mouse when Dockly's TUI starts?
