### ISSUE TITLE
When exiting dockly, MaxListenersExceededWarning is displayed

### ISSUE THREAD

**Issue by erikvullings** [lirantal/dockly#249]
### What went wrong?

erik@WS-91019:~$ dockly
(node:15356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 key listeners added to [myWidget]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

### Your environment setup

- Operating System: Ubuntu 22.04 (WSL2)
- Node.js version (run `node --version`): v18.17.0
- Package version: v3.23.1
- Docker version (run `docker --version`): 24.0.4
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`:
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 27
  Running: 27
  Paused: 0
  Stopped: 0
 Images: 26
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 102.2GiB
 Name: WS-91019
 ID: d12c9113-d04f-47bc-839a-f349b2b1f0c4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by lirantal** [comment]
I noticed it today too. 
Will need more investigation.

**Comment by lirantal** [comment]
Ok, so, this is definitely not a memory leak or a bug, it's just a warning.
We indeed set exactly 11 event emitter listeners related to the toolbar (for key commands): 
<img width="1351" alt="image" src="https://github.com/lirantal/dockly/assets/316371/470fdd6b-33da-4744-89b5-74de36404a6d">


I'll update the code to increase the internal limit for event listeners so it doesn't show this warning.
Thanks for reporting @erikvullings 🤗
