### ISSUE TITLE
Dockly crashes when toggling between views

### ISSUE THREAD

**Issue by erikvullings** [lirantal/dockly#250]
### What went wrong?

I've started dockly, restarted some containers or opened the shell and displayed several logs. Next, I toggle the view, and the (empty) services tab is shown. I toggle the view again, and dockly crashes. This is not easily reproducible. Sometimes, I can switch multiple times without a problem, sometimes it crashes. See the error report below:

```bash
(node:133822) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 key listeners added to [myWidget]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:133822) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 key listeners added to [myWidget]. Use emitter.setMaxListeners() to increase limit

dockly 3.23.1
Usage: dockly [OPTIONS]

dockly

  Immersive terminal interface for managing docker containers and services

Options

  -s, --socketPath string     Docker daemon socket to connect to
  -H, --host string           Remote docker daemon host to connect to
  -P, --port number           Remote docker port to connect to
  -T, --protocol              Remote docker protocol to connect to
  -h, --help                  Display this usage guide.
  -v, --version               Display version
  --containerFilters string   Filter containers
  --theme string              Theme: light or dark (e.g. --theme light)

  Project home: https://github.com/lirantal/dockly


Trace: TypeError: Cannot read properties of undefined (reading 'update')
    at myWidget.updateItemLogs (/home/erik/.nvm/versions/node/v18.17.0/lib/node_modules/dockly/widgets/containers/containerList.widget.js:27:49)
    at IncomingMessage.<anonymous> (/home/erik/.nvm/versions/node/v18.17.0/lib/node_modules/dockly/src/widgetsTemplates/list.widget.template.js:53:18)
    at IncomingMessage.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at HTTPParser.parserOnBody (node:_http_common:131:24)
    at Socket.socketOnData (node:_http_client:541:22)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at exitError (/home/erik/.nvm/versions/node/v18.17.0/lib/node_modules/dockly/index.js:88:13)
    at process.<anonymous> (/home/erik/.nvm/versions/node/v18.17.0/lib/node_modules/dockly/index.js:37:7)
    at process.emit (node:events:526:35)
    at process._fatalException (node:internal/process/execution:149:25)
```

### Your environment setup

- Operating System: Ubuntu 22.04 (WSL2)
- Node.js version (run `node --version`): v18.17.0
- Package version: v3.23.1
- Docker version (run `docker --version`): 24.0.4
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`:
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 27
  Running: 27
  Paused: 0
  Stopped: 0
 Images: 26
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 102.2GiB
 Name: WS-91019
 ID: d12c9113-d04f-47bc-839a-f349b2b1f0c4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by lirantal** [comment]
I'm not entirely sure why this is happening. I was unable to reproduce a crash myself but I've put some guardrails before attempting to render or update any of the container logs as it shows in your stack trace.
