### ISSUE TITLE
Feature request: Podman support

### ISSUE THREAD

**Issue by erikvullings** [lirantal/dockly#253]
Podman, which is in many ways a Docker alternative (without requiring root access), has a very similar CLI as Docker. Could dockly show them too, potentially even in the same view as the docker containers?

**Comment by lirantal** [comment]
@erikvullings this was already added a while back by @OmriBarZik in PR https://github.com/lirantal/dockly/pull/172

Can you follow his PR descriptions for usage and test it?
If it works as expected, it would be great to then update the README with docs about Podman support
