### ISSUE TITLE
[Bug]: Containers Utilization not working

### ISSUE THREAD

**Issue by vanlueckn** [lirantal/dockly#266]
### What went wrong?

I have installed dockly with npm on Debian 12 ARM and Debian 12 amd64. 

The containers utilization is not working.

![image](https://github.com/lirantal/dockly/assets/53119369/182345f7-227d-4f04-86eb-b5e230a0e1d4)

### Your environment setup

- Operating System: Debian 12
- Node.js version (run `node --version`): v18.13.0
- Package version: 3.23.5
- Docker version (run `docker --version`): Docker version 24.0.5, build ced0996
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? yes
- Output of `docker info`:

```
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 18
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-10-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.25GiB
 Name: web-worker-amd64-1
 ID: f8a93a93-6331-4154-9108-929a4a15b563
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by lirantal** [comment]
Thanks for bringing this up @vanlueckn 

I was indeed able to figure out that the counting has been deprecated in the way that it matched available cpu cores, and I've updated the code to match.

Comparing it between dockly and the official docker desktop extension I can see the same numbers:

<img width="326" alt="image" src="https://github.com/lirantal/dockly/assets/316371/a2083080-724c-4357-a8aa-a2a35531340a">

![image](https://github.com/lirantal/dockly/assets/316371/70cb6b85-d881-423d-ac34-0203b142a393)

Pushing a fix in a second

**Comment by lirantal** [comment]
Released in a new version 🎉

**Comment by vanlueckn** [comment]
Thank you!
