### ISSUE TITLE
Toggle view mode button is missing on services view

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#35]
## Expected Behavior
When I am toggling the view mode to the 'services' view I don't see the same bottom menu button (to help me know how to toggle view mode again)

## Actual Behavior
Toggle view mode is a primary button on all screens

## Steps to Re-produce the Problem

  1. Run dockly

  2. Toggle the view mode for the services view

  3. No 'toggle view' mode menu item 

![image](https://user-images.githubusercontent.com/316371/34767128-0645fdcc-f600-11e7-8924-b622bc02922d.png)

**Comment by MatanAvneri** [comment]
Closing this issue, fixed in #36
