### ISSUE TITLE
Dockerfile is not idempotent and doesn't match the source

### ISSUE THREAD

**Issue by oppianmatt** [lirantal/dockly#38]
It installs dockly via npm here

https://github.com/lirantal/dockly/blob/ad07b4ab470b05e02e4088f03c07e06c6a0d957a/Dockerfile#L4

But really shouldn't it use the dockly that's packaged in the source along with the Dockerfile? So when you build using a CI the source for the docker matches source in your repository, not some random npm version depending on what was pushed for the day.

**Comment by lirantal** [comment]
Mostly definitely!

And thanks for chiming in on this. Do you want to open a PR to fix the dockerfile?

**Comment by lirantal** [comment]
Fixed, thanks!
