### ISSUE TITLE
Crash: SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by salarelv** [lirantal/dockly#41]
## Expected Behavior
Launching the app

## Actual Behavior
dockly 3.2.1
Usage: dockly [OPTIONS]

dockly

  Interactive shell for managing Docker containers 

Options

  -s, --socketPath string   Docker daemon socket to connect to 
  -h, --help                Display this usage guide.          
  -v, --version             Display version                    

  Project home: https://github.com/lirantal/dockly 

Trace: /usr/local/lib/node_modules/dockly/widgets/toolbar.widget.js:86
        ...commands,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at glob.sync.forEach (/usr/local/lib/node_modules/dockly/src/assetsLoader.js:30:46)
    at exitError (/usr/local/lib/node_modules/dockly/index.js:79:13)
    at initDockerConnection.then.then.catch (/usr/local/lib/node_modules/dockly/index.js:32:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)

## Context

- Operating System: Ubuntu 16.04
- Node.js version (run `node --version`): 6.12.3
- Package version:
- Docker version (run `docker --version`): 17.12.0
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? yes
- Output of `docker info`:

Containers: 37
 Running: 5
 Paused: 0
 Stopped: 32
Images: 168
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 367
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.42GiB
Name: T430
ID: Y423:LBP2:OSYM:7QAL:5BUC:LM6Q:5UWE:DDJL:RDRI:GNLB:XK2B:3RMH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by lirantal** [comment]
Hey @salarelv 

We're only supporting Node.js version 8 due to requiring recent language features such as spread operator, async/await, etc.

Are you able to upgrade to to Node.js 8?

**Comment by salarelv** [comment]
OK. 
Have you consider about using pkg to package it to single executable?

**Comment by lirantal** [comment]
I didn't consider that, is it something you would like to try and work on or should I take a stab at it?

**Comment by salarelv** [comment]
Tried it out. Seems that pkg doesn't support ES6 or I am doing something wrong:
> Error! Unexpected token (86:8)
  /home/taavi/oss/dockly/widgets/toolbar.widget.js

**Comment by salarelv** [comment]
PS! Latest node version for pkg is node9.

**Comment by lirantal** [comment]
`pkg` seems to complain about the same javascript syntax as you originally posted for Node.js v6.12.3

I'm not familiar with pkg yet, but did you provide it with something like `--targets node8` so that maybe it bundles the code for that?

**Comment by salarelv** [comment]
Yes I tried with node8 and latest.
I have done a project with pkg before so I know it works.

**Comment by lirantal** [comment]
this is the feature we're using:
![image](https://user-images.githubusercontent.com/316371/35428109-fa30a460-0275-11e8-9d65-17f8cdd51f63.png)

@salarelv can you try a supported version from that list? say 8.9.4 specifically and not just any random 8 or 9 version?

**Comment by salarelv** [comment]
pkg doesn't support more precise version. As I can read from their issues page they are at 8.9.0

**Comment by lirantal** [comment]
Gotcha. Let me push a quick fix for that and let's try it.

**Comment by lirantal** [comment]
@salarelv pushed and publish a new version, can you check?

**Comment by salarelv** [comment]
I made some changes in the dynamically loaded modules. So I have to merge it. Maybe tomorrow?

**Comment by lirantal** [comment]
sure :-)

**Comment by lirantal** [comment]
@salarelv I'm closing for now but would love to continue this if you're able to jump in on the conversation again and share the status.
