### ISSUE TITLE
Error message on Ubuntu 16.04

### ISSUE THREAD

**Issue by solarisfire** [lirantal/dockly#50]
## Expected Behavior
Dockly should run.

## Actual Behavior
root@neo:~# dockly
/usr/local/lib/node_modules/dockly/src/screen.js:36
  constructor (utils = new Map()) {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockly/index.js:10:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@neo:~# node --version
v4.2.6

## Steps to Re-produce the Problem

  1. Install Ubuntu 16.04
  2. Install docker and create some docker containers
  3. Install node, npm & dockly
  4. Run

## Context

- Operating System: Ubuntu 
- Node.js version (run `node --version`): v4.2.6 (current in Ubuntu 16.04 LTS)
- Package version: dockly@3.3.1
- Docker version (run `docker --version`): Docker version 1.13.1, build 092cba3
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? /var/run/docker.sock: socket (yes)
- Output of `docker info`:
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.32 GiB
Name: neo
ID: ***
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by lirantal** [comment]
Hey @solarisfire,

We support Node >= 7.6.0
Is it possible for you to upgrade to a more recent version of Node.js like 8?

**Comment by solarisfire** [comment]
Any chance you could put that in the package.json file so idiots like me get stopped at install?

I ended up just running inside a container for now. However it doesn't look quite right with all of the lines being replaced by x's.

I'll upgrade to nodejs 8 a bit later today. It's a bit of a pain on Ubuntu 16.04 as it installs 4.2.6 by default.

**Comment by solarisfire** [comment]
![dockly](https://user-images.githubusercontent.com/420952/36560203-086e774e-1808-11e8-8335-7cf5de116a6b.JPG)

Running in nodejs 8 now. Doesn't look as pretty as the screenshots though :(

**Comment by lirantal** [comment]
woohoo 🎉 😄 
that does look kinda odd though heh

@solarisfire we do have it on the package.json, in the form of:
`
  "engines": {
    "node": ">=7.6.0"
  },
`

but not all package managers respect it, or some would just show an warning during install but will still proceed with installing it.

We also show a Node.js version badge on the README but I guess it's easy to miss too.

**Comment by lirantal** [comment]
I'll close for now but please feel free to re-open if there's anything more we can help with.

**Comment by theFra985** [comment]
Hi,
I've found the "bad grapic" using PuTTY on windows.
Although using the windows cmd (with the linux subsystem) the interface works better!
I don't know if it can be useful but i noticed that so... ¯\\\_(ツ)\_/¯

**Comment by lirantal** [comment]
thanks! useful to know ;-)

**Comment by norweeg** [comment]
@lirantal  @theFra985 @solarisfire I have a solution for bad GUI drawing in PuTTY.  In your session settings, you need to check the following box:
![image](https://user-images.githubusercontent.com/5969754/65817353-fff36100-e1d3-11e9-958d-9d241e973ec9.png)

**Comment by lirantal** [comment]
thanks @norweeg 👍✨
