### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by j796160836** [lirantal/dockly#54]
## Expected Behavior

It should runs normal.

## Actual Behavior

I encountered the `SyntaxError: Use of const in strict mode.` error and can't solve at my end.

```
$ dockly

/usr/local/lib/node_modules/dockly/index.js:7
const semver = require('semver')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

## Steps to Re-produce the Problem

  1. I use my Mac and install dockly via npm

```
$ sudo npm install -g dockly
```

  2. Run `dockly` and shows the error above.

  3. I'm tried install the lack package `semver` and run again, but not work.

```
$ sudo npm install -g semver
$ dockly
```

## Context

- Operating System:
Mac OS X 10.13.4 (High Sierra)
- Node.js version (run `node --version`):
v0.10.33
- Package version:
dockly v3.3.2
- Docker version (run `docker --version`):
Docker version 18.03.0-ce, build 0520e24
- Is docker installed locally?
Yes.
- Do you have containers created?
Yes.
- Does this file exists `/var/run/docker.sock` ?
Yes.
- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 41
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: JDUG:AY3N:4CYB:UOUU:O4WA:CVHK:ODWS:FQ6I:3H67:KKH7:ZNBI:7VTD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by lirantal** [comment]
@j796160836 you're running an extremely old version of Node.js (`Node.js version (run node --version): v0.10.33`)

Can you upgrade to the latest LTS? version 8
I recommend using [nvm](https://github.com/creationix/nvm) for this

**Comment by lirantal** [comment]
@j796160836 did you work it out?
let me know if there's a way for me to help

**Comment by j796160836** [comment]
Thanks Liran,
After updates nodeJS and everything seems happy. 🙂
```
 $ brew install node
```
My node version updated to v9.11.1.
Thanks again.
