### ISSUE TITLE
The actions menu display/hide isn't consistent

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#60]
## Expected Behavior
Toggling on/off the actions menu with the `m` key should work as expected.

## Actual Behavior
When toggling the menu to display, and then hiding it with `esc` key, clicking again the `m` key to display it doesn't work.

**Comment by guyzmo** [comment]
(if you `m` a second time it appears, though)

**Comment by lirantal** [comment]
Right. It's a simple fix too.
Basically what's missing is that it is required to listen to both the `escape` key and the `m` keypress to toggle the visibility variable.
