### ISSUE TITLE
Shell launches xcode editor w dockerRunScript.sh

### ISSUE THREAD

**Issue by zanedev** [lirantal/dockly#76]
## Expected Behavior
Actual shell launches

## Actual Behavior
Xcode pops up with the run script code in it instead of executing
![image](https://user-images.githubusercontent.com/817344/45699913-07435180-bb20-11e8-8965-db6996dad50a.png)

## Steps to Re-produce the Problem

  1. Load dockly

  2. Choose container

  3. Run shell command

## Context

- Operating System: Mac High Sierra
- Node.js version (run `node --version`): v8.9.3
- Package version: dockly@3.8.0
- Docker version (run `docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`: 
```
Containers: 30
 Running: 28
 Paused: 0
 Stopped: 2
Images: 33
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: SRTA:C3MC:5ZBY:ZMKQ:4YZV:DMKZ:5YWF:2X2B:FOOQ:R57F:QSNV:ZAVT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 249
 Goroutines: 226
 System Time: 2018-09-18T15:53:42.2246559Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by lirantal** [comment]
Hi @zanedev,

This is happening because in your Mac `xcode` is set as the default launcher for file types associated with a `.sh` extension.

There's an easy way to change that, I found [this](https://www.laptopmag.com/articles/how-to-change-default-applications-mac) as the first google search result
