### ISSUE TITLE
Integrate with Dive

### ISSUE THREAD

**Issue by sbernheim4** [lirantal/dockly#80]
This is really cool. Thanks for your work! I also know of this other great CLI tool called [dive](https://github.com/wagoodman/dive) which lets you inspect the file system of a docker image at each layer. 

It would be really cool if you could integrate this feature via a keybinding/command. I think this would bring a lot of utility to a high level tool like this.

**Comment by lirantal** [comment]
Hi @sbernheim4,

Thanks for the warm words :)
Dive looks great!

It would probably be quite a bit of work to add support for that level of file browsing. Not too sure about having a special binding for Dive as that could result as somewhat of a grief for the user in cases where that tool isn't installed.

Happy to hear more feedback on this though.

**Comment by lirantal** [comment]
Happy to discuss more about this or other ideas. Will close for now.
