### ISSUE TITLE
Pressing `l` to open shell runs `xdg-open` on Linux

### ISSUE THREAD

**Issue by zacanger** [lirantal/dockly#81]
## Expected Behavior

The script should be spawned.

## Actual Behavior

The script is opened with xdg-open on Linux, and the default handler on Mac (XCode, I think). On my computer, xdg-open ends up trying to open the script in Chromium, which then tries to download the script.

Related issues: #76, #55, possibly #65.

Rather than using open [here](https://github.com/lirantal/dockly/blob/v3.8.0/hooks/shell.hook.js#L29), I believe `child_process.spawn` would work. `opn` calls `open` on Darwin, `xdg-open` if it's available, and whatever the Windows equivalent is on Windows. For a shell script, that could be anything from an IDE to spawning a terminal that runs Vim to not even having a good default (like on my machine).

Using `child_process.spawn` would mean running in the same window rather than trying to open a new terminal. `child_process.exec` could be used to open a new terminal, but would require a good bit of logic (check platform, try to figure out the correct terminal, etc).

## Steps to Re-produce the Problem

  1. Run Dockly on Linux without setting a handler for shell files
  2. Try to launch a shell through Dockly

## Context

- Operating System:
- Node.js version (run `node --version`): 10.12.0
- Package version: 3.8.0
- Docker version (run `docker --version`): 10.06.1-ce
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? Yes
- Output of `docker info`: Not relevant

**Comment by lirantal** [comment]
Thanks @zacanger for opening this issue again.
That is indeed an issue that has been repeating and I can see how much grief it can add.

I don't think `spawn` is going to be helpful in this case.
Maybe it's worth it to try and whitelist some terminal program paths and names and try to execute those?

**Comment by lirantal** [comment]
yep, what do you think?
I was actually thinking that I don't need to even check the OS, just try running the shell script with one of them and as the promise fails just try another app one by one, until the OS will solve with the app that is tied to this filetype.

**Comment by lirantal** [comment]
@zacanger I pushed a fix.
Can you `npm install -g dockly@3.8.1` and confirm if the terminal launching works for you now?

**Comment by zacanger** [comment]
That works! I'm on a Mac right now, but the change looks like it should be perfectly fine on Linux too. Thanks!

**Comment by lirantal** [comment]
Awesome! thank you for the quick response in confirming.
Let me know if you find other issues or ideas to improve - I'll be happy to hear :)
