### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#9]
When loading a list of containers that are unreachable, or navigating in the containers list on non-running containers then the widget for reading cpu/memory metrics is trying to access properties of the container but it can't, so dockly quits with:

```bash
Error: Cannot read property 'length' of undefined
```

**Comment by cjus** [comment]
I experienced this one too.

**Comment by lirantal** [comment]
Thanks for confirming. I already fixed that in a local version, I'll push the fix within a day, just want to test it some more.
