### ISSUE TITLE
Light mode theme needed

### ISSUE THREAD

**Issue by keithy** [lirantal/dockly#92]
Dockly doesn't display well in a terminal using light colouring.

**Comment by lirantal** [comment]
should we perhaps have support for themes?
if so, how would we control that? cmd line arguments?

**Comment by NightMachinary** [comment]
@lirantal I suggest adding a simple --light-mode that uses colors that are friendly with most light-themed terminals. `glances` does this via `--theme-white`.

**Comment by lirantal** [comment]
I like this. Would be happy to get a PR for this.

**Comment by jscooksey** [comment]
I would like to take a look at this.  I wont be quick, as the 9-5 job is pretty busy at present, but I'll keep you up to date if required.

**Comment by lirantal** [comment]
@jscooksey awesome. Would love to merge it if you push it in and take your time to spend with family too, don't need to rush this ❤️

Ping me for anything you'd like to consult or run ideas off while you're working on it.
A general suggestion is to be able to support several themes, and so you could allow for a configuration of colors, and then load a default or a specific one based on ENV VARS or command line options.

**Comment by lpjune** [comment]
is anyone still working on this? wanna check it out but don't wanna steal it from someone!

**Comment by lirantal** [comment]
@lpjune doesn't seem like it... ?
I'd be happy to merge if you want to pick it up

**Comment by jscooksey** [comment]
Please go ahead, I did make a start but haven’t been able to get time to get in to it.  Apologies.

**Comment by sebastian-curland** [comment]
I'll give it a try

**Comment by sebastian-curland** [comment]
https://github.com/lirantal/dockly/pull/150

**Comment by lirantal** [comment]
Fixed in #150
